Fix delete
openshift-hive/hypershift pull request #36
Opened 2021-01-18 13:37 UTC by enxebre

This lets the nodePool controller to explicitly delete its owned machineSet. Removing the owner ref is not enough as it has other from the cluster resource.

It also move the default nodePool to be created by the openshiftCluster controller. Otherwise openshiftCluster deletion is not able to delete de default nodePool.

We are blocking it on https://github.com/openshift-hive/hypershift/blob/main/hypershift-operator/controllers/infra.go#L42 though the ign endpoint will only be given after deploying the service which is only applied after that https://github.com/openshift-hive/hypershift/blob/main/hypershift-operator/controllers/hosted_controlplane_controller.go#L156
This results in a deadlock loop which is broken by this PR.

Remove foreground deletion and relax timeouts for e2e

2021-01-18 15:49 UTC, csrwng requested changes
Hey @enxebre looks good. Some nits, also why do we want to remove foreground deletion in the e2e?

2021-01-18 15:49 UTC, csrwng commented on hypershift-operator/controllers/nodepool_controller.go
> +				return ctrl.Result{}, fmt.Errorf("failed to remove finalizer from cluster: %w", err)
nit: "failed to remove finalizer from nodepool"

2021-01-18 15:49 UTC, csrwng commented on hypershift-operator/controllers/nodepool_controller.go
> +		r.Log.Info("Delete machineSet", "machineset", machineSet.GetName())
nit: "Deleted"

2021-01-18 15:49 UTC, csrwng commented on hypershift-operator/controllers/nodepool_controller.go
> +	// Ensure the cluster has a finalizer for cleanup
nit: s/cluster/nodepool/

2021-01-18 15:49 UTC, csrwng commented on hypershift-operator/controllers/nodepool_controller.go
> +			return ctrl.Result{}, fmt.Errorf("failed to add finalizer to cluster: %w", err)
nit: s/cluster/nodepool/

2021-01-18 15:49 UTC, csrwng commented on hypershift-operator/controllers/openshiftcluster_controller.go
> +		return fmt.Errorf("failed to delete cluster: %w", err)
nit: s/cluster/nodepool/

2021-01-18 15:49 UTC, csrwng commented on hypershift-operator/controllers/openshiftcluster_controller.go
> +			Name:      fmt.Sprintf("%v-default", name),
s/%v/%s/

2021-01-18 15:49 UTC, csrwng commented on hypershift-operator/controllers/infra.go
> -		len(s.IgnitionProviderAddress) > 0
we can drop the check, but we should also get the route hostname from the spec instead of status

2021-01-19 09:41 UTC, enxebre commented
>Hey @enxebre looks good. Some nits, also why do we want to remove foreground deletion in the e2e?

I believe with foreground deletion the garbage collector deletes all the capi cluster resource dependents automatically breaking the capi cluster deletion enforced ordering.

2021-01-19 14:43 UTC, csrwng commented
/lgtm

2021-01-19 14:43 UTC, merged